services:
  db:
    image: pgvector/pgvector:pg18-trixie
    container_name: mmds_db_container
    restart: always
    environment:
      - POSTGRES_DB=male_voice_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
